### ISSUE TITLE
Improvement - Some methods can be moved out of the game object

### ISSUE THREAD

**Issue by edvinalestig** [edvinalestig/gymnasiearbete#45]
Some methods like point calculation and word finding can be moved out of the game object into a module or similar. If many game instances are running at the same time the non-game-specific methods can be shared instead of having a copy for each game.

Low priority

**Comment by itggot-edvin-alestig** [comment]
The classes should be restructured. Some methods are placed in the game class which make more sense to be placed in the other classes.

**Comment by edvinalestig** [comment]
The methods for calculating points have been moved to a Utility class. Anything else?
