### ISSUE TITLE
The response method in game.rb should not return a hash if the player forfeited.

### ISSUE THREAD

**Issue by edvinalestig** [edvinalestig/gymnasiearbete#57]
The method should return a bool and instead change the winner variable. A check will see if the winner has been determined later in the code.

A method should only return one datatype, which it currently does not.

**Comment by itggot-edvin-alestig** [comment]
Other methods should also be rewritten to only return one datatype.

**Comment by edvinalestig** [comment]
The methods now return a Response object instead of bools and hashes.
